export const items = [

  {
    id: 1,
    category: 'mobiles',
    title: "Apple iPhone 14",
    imgSrc: 'https://rukminim2.flixcart.com/image/850/1000/ktketu80/mobile/2/y/o/iphone-13-mlpk3hn-a-apple-original-imag6vpyur6hjngg.jpeg?q=20&crop=false',
    return: '3 days retun available',
    description: 'Apple iPhone 14 (128 GB) - Blue Apple',
    original_price: '89999',
    current_price: '59999',
    discount: '30',
  },
  {
    id: 32,
    category: 'watch',
    title: " Mikado watch",
    imgSrc: 'https://img0.junaroad.com/uiproducts/18689620/zoom_0-1669009918.jpg',
    return: '4 days retun available',
    description: 'MIKADO Analog Watch - For Men - Buy MIKADO Analog Watch',
    original_price: '69999',
    current_price: '59999',
    discount: '20',
  },
  {
    id: 33,
    category: 'Television',
    title: "Collins television",
    imgSrc: 'https://static.digit.in/product/62fbd1bbab2478964564641957db61ce84794b94.jpeg',
    return: '5 days retun available',
    description: 'Panel Mount Rectangle TELEVISION, Screen Size: 32 at Rs 14500/piece  ',
    original_price: '69999',
    current_price: '59999',
    discount: '20',
  },
  {
    id: 37,
    category: 'Fans',
    title: "Usha Fan",
    imgSrc: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCPybfdkxnyI3AEX_gxiCTfr3JYNRwcnAbEA&s',
    return: '6 days retun available',
    description: 'Buy Bajaj Frore 1200 mm (48") 1 star Rated Ceiling Fans for Home',
    original_price: '69999',
    current_price: '59999',
    discount: '20',
  },
  {
    id: 5,
    category: 'laptops',
    title: "Xiaomi [Smartchoice] Notebookpro",
    imgSrc: 'https://furper.com/cdn/shop/products/xiaomi-notebook-pro-156-inch-laptop-2020-intel-core-i7-16gb-1tb-mx350-laptop-xiaomi-796657_large.jpg?v=1596582001',
    return: '7 days retun available',
    description: 'Xiaomi Notebook Pro 15.6 Inch Laptop 2020 Intel Core i7',
    original_price: '89999',
    current_price: '59999',
    discount: '42',
  },
  {
    id: 9,
    category: 'tablets',
    title: "Xiaomi Pad 5",
    imgSrc: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOCmAchQa_t2fKraYGMjNLf8gG9mtlIs0Tag&s',
    return: '8 days retun available',
    description: 'Xiaomi Pad 6| Qualcomm Snapdragon 870| ',
    original_price: '89999',
    current_price: '59999',
    discount: '50',
  },
  {
    id: 13,
    category: 'Shrit',
    title: "Mens Cotton Navy",
    imgSrc: 'https://assets.ajio.com/medias/sys_master/root/20230526/B4Il/6470407e42f9e729d7e3505b/-473Wx593H-465504189-green-MODEL.jpg',
    return: '9 days retun available',
    description: 'Mens Cotton Navy Blue Fashion Shirt at Rs 380 in Jaipur |',
    original_price: '89999',
    current_price: '59999',
    discount: '50',
  },

  {
    id: 2,
    category: 'mobiles',
    title: "Samsung Galaxy A23 5G",
    imgSrc: 'https://www.jiomart.com/images/product/original/493664931/samsung-galaxy-a23-5g-128-gb-8-gb-ram-silver-mobile-phone-digital-o493664931-p597885912-0-202301260956.jpeg?im=Resize=(420,420)',
    return: '10 days retun available',
    description: 'Buy Samsung Galaxy A23 5G 128 GB, 8 GB RAM, Silver, Mobile Phone ',
    original_price: '79999',
    current_price: '59999',
    discount: '60',
  },
  {
    id: 17,
    category: 'Pant',
    title: "JEANS PANT",
    imgSrc: 'https://rukminim2.flixcart.com/image/850/1000/xif0q/jean/w/j/h/32-007-super-mack-original-imaggy6c2cq5gngn.jpeg?q=90&crop=false',
    return: '11 days retun available',
    description: 'SUPER MACK Regular Men Dark Blue Jeans - Buy  ',
    original_price: '69999',
    current_price: '59999',
    discount: '20',
  },
  {
    id: 21,
    category: 'T-shrit',
    title: "T-Shirts for Men",
    imgSrc: 'https://m.media-amazon.com/images/I/51LalJKnXlL._AC_UY1100_.jpg',
    return: '12 days retun available',
    description: 'Buy Thewalkdeal Pack of 6 Plain T-Shirts for Men Multi-Colour at ',
    original_price: '69999',
    current_price: '59999',
    discount: '20',
  },
  {
    id: 25,
    category: 'Shoes',
    title: "NIKE Shoes",
    imgSrc: 'https://www.campusshoes.com/cdn/shop/files/CHANCE_22G-1068_WHT-T.BLU_2.jpg?v=1689246379',
    return: '13 days retun available',
    description: 'Buy Black Sports Shoes for Men by NIKE Online in India at Rs. 6,071.',
    original_price: '69999',
    current_price: '59999',
    discount: '20',
  },
  {
    id: 31,
    category: 'watch',
    title: "ROLEX  Watch",
    imgSrc: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRY2WIXdcq2odLOuLdDr4GwXmnY2qqLHrWKfg&s',
    return: '14 days retun available',
    description: 'Rolex Watch - Buy Rolex Watch For Men Online India - Dilli Bazar',
    original_price: '69999',
    current_price: '59999',
    discount: '20',
  },

  {
    id: 3,
    category: 'mobiles',
    title: "Realme C35 64 GB",
    imgSrc: 'https://www.jiomart.com/images/product/original/492849559/realme-c35-64-gb-4-gb-ram-glowing-green-mobile-phone-digital-o492849559-p591223038-0-202204202315.jpeg?im=Resize=(420,420)',
    return: '3 days retun available',
    description: 'Realme C35 64 GB 4GB of RAM and 64GB of storage ',
    original_price: '79999',
    current_price: '59999',
    discount: '80',
  },
  {
    id: 6,
    category: 'laptops',
    title: "ASUS Zenbook 14 UX425",
    imgSrc: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRaX6sHwIB2AsWcAkc-fzKvRhmSpNMO57KI7Q&s',
    return: '4 days retun available',
    description: 'Buy ASUS Zenbook 14 UX425, 11th Gen Intel Best laptop for home| ASUS India',
    original_price: '89999',
    current_price: '59999',
    discount: '42',
  },
  {
    id: 10,
    category: 'tablets',
    title: "Tablet Samsung Galaxy",
    imgSrc: 'https://images.tokopedia.net/img/cache/700/OJWluG/2023/1/2/3a3e7e0c-af15-408f-9929-ae7a3713964c.jpg',
    return: '5 days retun available',
    description: 'Breve Análise do Tablet Samsung Galaxy Tab S5e (Wi-Fi)',
    original_price: '89999',
    current_price: '59999',
    discount: '50',
  },
  {
    id: 44,
    category: 'AC',
    title: "Window AC",
    imgSrc: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRX7_Eiodk698TOX_I52llefFwJBMd3ettNpw&s',
    return: '6 days retun available',
    description: 'Window AC Buying Guide: 6 Things To Keep In Mind Before Buying One - Times of India  ',
    original_price: '69999',
    current_price: '59999',
    discount: '20',
  },
  {
    id: 39,
    category: 'Fans',
    title: "IndiaMART fans",
    imgSrc: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUoF2dVW9pDs_RyH54Dfvi83cn43yhSlptwg&s',
    return: '7 days retun available',
    description: 'Black Metal Mini Electric Fan at Rs 379/piece in Bengaluru |  ',
    original_price: '69999',
    current_price: '59999',
    discount: '20',
  },

  {
    id: 4,
    category: 'mobiles',
    title: "Motorola Moto G200 5G",
    imgSrc: 'https://www.zdnet.com/a/img/resize/ece88764140664d4f3409fa02a833937fdf1bdf1/2022/01/19/f9b0e477-826a-4de7-95f1-cd8ba6721d30/motorola-moto-g200-thumb.jpg?auto=webp&fit=crop&height=1200&width=1200',
    return: '8 days retun available',
    description: 'Motorola Moto G200 5G, hands on: Large screen, good specs, fair price ',
    original_price: '79999',
    current_price: '59999',
    discount: '80',
  },



  {
    id: 7,
    category: 'laptops',
    title: "HP Laptop 15",
    imgSrc: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSb9lYTakBxDl_HdYDXy-YtTvofxxPtLl0eUA&s',
    return: '9 days retun available',
    description: 'HP Laptop 15, 12th Gen i5-1235U, 15.6-inch (39.6 cm), FHD, Anti-Glare, 8GB DDR4, 512GB SSD',
    original_price: '89999',
    current_price: '59999',
    discount: '42',
  },

  {
    id: 36,
    category: 'Television',
    title: "Televisions | TechRadar ",
    imgSrc: 'https://www.reliancedigital.in/medias/ONEPLUS-43Y1-TV-491895011-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3wyNTQ5NHxpbWFnZS9qcGVnfGltYWdlcy9oOGQvaDZmLzk4MTAwNTg1NzU5MDIuanBnfDRlNjk2MTc0MjNiODNmYmZkNmVjNWQwMjM1N2QxMzExOWFkNzcyOTNiY2M3ODU0ZmUyN2Y5OWEyNjExNzFkYTY',
    return: '10 days retun available',
    description: 'Best TVs To Play With Your PS5 That You Can Buy Aroged, 53% OFF ',
    original_price: '69999',
    current_price: '59999',
    discount: '20',
  },
  {
    id: 14,
    category: 'Shrit',
    title: "Men Formal Shirts",
    imgSrc: 'https://assetscdn1.paytm.com/images/catalog/product/A/AP/APPBASICS-FORMABASI2008628C85E2B/1562766487989_4..jpg?imwidth=540&impolicy=hq',
    return: '11 days retun available',
    description: 'Sonis Very Good Men Formal Shirts at Rs 300 in Jamnagar ',
    original_price: '69999',
    current_price: '59999',
    discount: '20',
  },
  {
    id: 18,
    category: 'Pant',
    title: " Multi Cargo pocket Track Pant",
    imgSrc: 'https://images-cdn.ubuy.co.in/6528cb3e84087004210b6cde-tactical-pants-for-men-cotton-classic.jpg',
    return: '12 days retun available',
    description: 'Men Solid Lycra Stylish Multi Cargo pocket Track Pant | Men Track Pant |',
    original_price: '69999',
    current_price: '59999',
    discount: '20',
  },
  {
    id: 8,
    category: 'laptops',
    title: "Apple Macbook Air",
    imgSrc: 'https://images-cdn.ubuy.co.in/650188aee584193d8350a66b-2022-apple-macbook-pro-laptop-with-m2.jpg',
    return: '13 days retun available',
    description: 'Lenovo Tab are good tab for 8gb P12 Pro AMOLED (12.6 inch (32 cm), 8 GB), ',
    original_price: '79999',
    current_price: '59999',
    discount: '70',
  },
  {
    id: 22,
    category: 'T-shrit',
    title: " Minimal Yellow T-Shirt",
    imgSrc: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzUTV0u8or53kL0BLfu3GFGhA3T_Fu-YGX7A&s',
    return: '14 days retun available',
    description: 'RRR Logo Minimal Yellow T-Shirt (Left Pocket) XL',
    original_price: '69999',
    current_price: '59999',
    discount: '20',
  },





  {
    id: 11,
    category: 'tablets',
    title: "Android 3G Phone Tablets",
    imgSrc: 'https://images-cdn.ubuy.co.in/63ca32eb868e293cfa392175-tablet-10-1-inch-android-3g-phone.jpg',
    return: '3 days retun available',
    description: 'Tablet 10.1 Inch Android  Tablets with 32GB Storage Dual Sim Card ',
    original_price: '89999',
    current_price: '59999',
    discount: '50',
  },
  {
    id: 43,
    category: 'AC',
    title: "Health Air Cooling Systems",
    imgSrc: 'https://www.lg.com/content/dam/channel/wcms/in/images/split-ac/rs-q18knxe_amlg_eail_in_c/gallery/RS-Q18KNXE-Split-ac-Front-View-D-01.jpg',
    return: '2 days retun available',
    description: 'MSY-GN13VF 1ton , 5 Star and Inverter Mitsubishi Air Conditioner | Health Air India ',
    original_price: '69999',
    current_price: '59999',
    discount: '20',
  },
  {
    id: 40,
    category: 'Fans',
    title: "Polar Electric fan",
    imgSrc: 'https://www.polarelectric.in/media/catalog/product/cache/1/small_image/275x253/602f0fa2c1f0d1ba5e241f914e856ff9/2/1/211105-09_hr.png',
    return: '4 days retun available',
    description: 'Polar Electric - Decorative Ceiling fans | High Speed & Low Cost  ',
    original_price: '69999',
    current_price: '59999',
    discount: '20',
  },
  {
    id: 15,
    category: 'Shrit',
    title: "Formal Cotton Shirts",
    imgSrc: 'https://5.imimg.com/data5/EK/GW/MY-3777880/formal-cotton-shirts-500x500.jpg',
    return: '5 days retun available',
    description: 'Plain Full Formal Cotton Shirts, Size: 36 at Rs 350/piece in Ahmedabad | ',
    original_price: '69999',
    current_price: '59999',
    discount: '20',
  },
  {
    id: 30,
    category: 'watch',
    title: "Luxury Golden watch",
    imgSrc: 'https://www.jiomart.com/images/product/original/rvqcyvklz7/iloz-new-luxury-golden-round-dail-designer-diamond-studded-stainless-steel-belt-royal-look-premium-quality-party-wear-watch-for-men-and-wrist-analog-watch-for-boys-men-analog-watch-for-men-product-images-rvqcyvklz7-0-202210110322.jpg?im=Resize=(1000,1000)',
    return: '6 days retun available',
    description: 'ILOZ New Luxury Golden Round Dail designer Diamond studded stainless    ',
    original_price: '69999',
    current_price: '59999',
    discount: '20',
  },
  {
    id: 34,
    category: 'Television',
    title: "Pinterest television",
    imgSrc: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9_gsymRrHcxRxxHUNqVLr880FfCSQNF4-tA&s',
    return: '7 days retun available',
    description: 'Television lounge ideas - Best furniture for tv room | Decoração',
    original_price: '69999',
    current_price: '59999',
    discount: '20',
  },
  {
    id: 19,
    category: 'Pant',
    title: "Men's Casual pant",
    imgSrc: 'https://m.media-amazon.com/images/I/51G2JWZCzKL._AC_UY1100_.jpg',
    return: '8 days retun available',
    description: 'Apple MacBook Air Laptop M1 chip, 13.3-inch/33.74  ',
    original_price: '69999',
    current_price: '59999',
    discount: '20',
  },
  {
    id: 26,
    category: 'Shoes',
    title: "Campus  Shoes",
    imgSrc: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUEiWh2KQe1bYG8z_b5A9doeB0XsPJbeDVTw&s',
    return: '9 days retun available',
    description: 'Go for jogs, hit the gym or even play your favourite sport wearing this',
    original_price: '69999',
    current_price: '59999',
    discount: '20',
  },
  {
    id: 42,
    category: 'AC',
    title: "ECO Breeze AI Window Solar AC ",
    imgSrc: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQB6xtuXBjKN_V-psrCE2wNe8HGc8xCipZQIw&s',
    return: '10 days retun available',
    description: 'ECO Breeze AI Window Solar AC – Nexus Solar Energy ',
    original_price: '69999',
    current_price: '59999',
    discount: '20',
  },

  {
    id: 12,
    category: 'tablets',
    title: "ZONKO High-Tech Tablet",
    imgSrc: 'https://m.media-amazon.com/images/I/71iXwWcOy1L._AC_UF1000,1000_QL80_.jpg',
    return: '11 days retun available',
    description: 'ZONKO High-Tech 10.1 Inch Tablet, Unlocked 2G/3G/4G Network Phone ',
    original_price: '89999',
    current_price: '59999',
    discount: '50',
  },


  {
    id: 16,
    category: 'Shrit',
    title: "Green Cut N Sew Designer ",
    imgSrc: 'https://5.imimg.com/data5/KX/VU/KI/SELLER-38484684/design-shirt.jpg',
    return: '12 days retun available',
    description: 'Green Cut N Sew Designer Satin Cotton Shirt Green / XL ',
    original_price: '69999',
    current_price: '59999',
    discount: '20',
  },




  {
    id: 20,
    category: 'Pant',
    title: "Presidio Dress Pants",
    imgSrc: 'https://m.media-amazon.com/images/I/411YDkwb1yL._AC_UY1100_.jpg',
    return: '13 days retun available',
    description: 'Presidio Dress Pants Regular Fit - Thunder Grey ',
    original_price: '69999',
    current_price: '59999',
    discount: '20',
  },



  {
    id: 24,
    category: 'T-shrit',
    title: "Black T-shirt",
    imgSrc: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBU-PxKxOIfggvXtIWpMp5t8FZqTMZqijDpy5rBUaU7avCXG2EtKlwRdRyKhfrlz7wcCk&usqp=CAU',
    return: '14 days retun available',
    description: 'Smartees Printed, Typography Men Round Neck Black T-shirt',
    original_price: '69999',
    current_price: '59999',
    discount: '20',
  },


  {
    id: 27,
    category: 'Shoes',
    title: " PT School Shoes",
    imgSrc: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSENBonBiJhE2sUrlLXxoeFmZ0Clvngsa1dMQ&s',
    return: '3 days retun available',
    description: 'Big Boss Unisex White PT School Shoes, Canvas, Packaging  ',
    original_price: '69999',
    current_price: '59999',
    discount: '20',
  },


  {
    id: 29,
    category: 'watch',
    title: "Apple Watch",
    imgSrc: 'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/MT3D3ref_VW_34FR+watch-case-44-aluminum-midnight-cell-se_VW_34FR+watch-face-44-aluminum-midnight-se_VW_34FR?wid=752&hei=720&bgc=fafafa&trim=1&fmt=p-jpg&qlt=80&.v=ajJYOEQxYjNlejNwbWNnSU16d0NYaWhSbVIzRFJTYlp1MEk4OWNDaTcvNTlEbzMrd1Z5SUpEd0hiT0ZLRlZGNHVDTzRRaC84T1VMbXJRN05SRldIelBRWnNWZWtLcTZCYVRER3FsWWowaTk5RG8zK3dWeUlKRHdIYk9GS0ZWRjR4cVNUNDJadDNVSmRncE9SalAvZ24zZmdHMUt6VFlqa3BpV2VBOUNycGdrcDIxSk5peW5HTWQ0c004MmJwMkNtdGl6SHg4ZE5NYmlWSVQ5akRTdGpCZkNDUmN0SlpnYXpQNFNTbUVsbTlnST0=',
    return: '4 days retun available',
    description: 'Apple Watch SE GPS + Cellular 44mm Midnight Aluminium Case  ',
    original_price: '69999',
    current_price: '59999',
    discount: '20',
  },





  {
    id: 35,
    category: 'Television',
    title: "Adobe Stock television",
    imgSrc: 'https://t4.ftcdn.net/jpg/05/02/26/29/360_F_502262924_FStXklnWAu66ZxI2CJOkQ9teE8Vv4hrF.jpg',
    return: '5 days retun available',
    description: 'Tv Images – Browse 1,852,902 Stock Photos, Vectors, and Video  ',
    original_price: '69999',
    current_price: '59999',
    discount: '20',
  },


  {
    id: 38,
    category: 'Fans',
    title: "IndiaMART fans",
    imgSrc: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxU4326YCriwxhjL43bKiuRdpskFmSHyePIw&s',
    return: '6 days retun available',
    description: 'Brown 600 mm 24inch Ceiling Fan, 600 RPM at  in New Delhi ',
    original_price: '69999',
    current_price: '59999',
    discount: '20',
  },


  {
    id: 41,
    category: 'AC',
    title: "Split AC Inverter",
    imgSrc: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjLUjb7jOFkG7UgX373riCc1KY6XZZMV78tA&s',
    return: '7 days retun available',
    description: 'Split AC Inverter - 1.0 - 3 Star Element (GLS12I3FWSEA) - Shop Home & Kitchen Appliance  ',
    original_price: '69999',
    current_price: '59999',
    discount: '20',
  },

  {
    id: 23,
    category: 'T-shrit',
    title: " Navy Blue S",
    imgSrc: 'https://chriscross.in/cdn/shop/files/95_800x.jpg?v=1695712761',
    return: '8 days retun available',
    description: 'Chris Cross Men s Plain T-Shirt: Navy Blue S',
    original_price: '69999',
    current_price: '59999',
    discount: '20',
  },
  {
    id: 28,
    category: 'Shoes',
    title: "School Shoes",
    imgSrc: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMjir2DESyEGTvpyadXJeGO_9yABl_Q6irog&s',
    return: '14 days retun available',
    description: 'To supply the ever rising needs of our customers, we are occupied  ',
    original_price: '69999',
    current_price: '59999',
    discount: '20',
  },

]